version: 0.0
os: linux
file_exists_behavior: OVERWRITE

files:
  - source: /
    destination: /home/ubuntu/hothyfa-cv

permissions:
  - object: /home/ubuntu/hothyfa-cv
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStop:
    - location: scripts/stop_app.sh
      timeout: 180
      runas: ubuntu

  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 600
      runas: ubuntu
    - location: scripts/build_app.sh
      timeout: 900
      runas: ubuntu

  ApplicationStart:
    - location: scripts/start_app.sh
      timeout: 180
      runas: ubuntu